memory_limit = 512M
upload_max_filesize = 128M
post_max_size = 128M
max_execution_time = 300
max_input_vars = 5000

display_errors = Off
log_errors = On

opcache.enable = 0
opcache.validate_timestamps = 1

extension = /opt/miyaui/ixed.8.0.lin
